### ISSUE TITLE
Authenticated Playground user goes over daily request limit throws an UI error

### ISSUE THREAD

**Issue by gloveboxes** [microsoft/azure-openai-service-proxy#133]
when the user has successfully authenticated in the playground and then they go over there request limit for the day - they get the following as they now fail authentication..

TypeError: Cannot read properties of undefined (reading 'innererror')
    at createErrorMessage (http://localhost:4280/src/pages/playground/Chat.reducers.ts:3:28)
    at reducer (http://localhost:4280/src/pages/playground/Chat.reducers.ts:66:18)
    at updateReducer (http://localhost:4280/node_modules/.vite/deps/chunk-XE5K45DR.js?v=ee1623f6:12417:30)
    at Object.useReducer (http://localhost:4280/node_modules/.vite/deps/chunk-XE5K45DR.js?v=ee1623f6:13360:24)
    at useReducer (http://localhost:4280/node_modules/.vite/deps/chunk-NVDSUZN5.js?v=ee1623f6:1070:29)
    at Chat (http://localhost:4280/src/pages/playground/Chat.tsx:36:29)
    at renderWithHooks (http://localhost:4280/node_modules/.vite/deps/chunk-XE5K45DR.js?v=ee1623f6:12171:26)
    at updateFunctionComponent (http://localhost:4280/node_modules/.vite/deps/chunk-XE5K45DR.js?v=ee1623f6:14577:28)
    at beginWork (http://localhost:4280/node_modules/.vite/deps/chunk-XE5K45DR.js?v=ee1623f6:15912:22)
    at beginWork$1 (http://localhost:4280/node_modules/.vite/deps/chunk-XE5K45DR.js?v=ee1623f6:19749:22)

**Comment by aaronpowell** [comment]
What response code are you returning? It should probably be a `429` but we should look at the AOAI Service spec to see how it handles rate limits being exceeded.
